MAKET_TABLE MAKET_DIV
fd1-44-17-group/morozoval pull request #13
Opened 2017-09-24 16:12 UTC by MorozovAl

please review

2017-09-27 05:11 UTC, fd1-44-17 requested changes

2017-09-27 05:11 UTC, fd1-44-17 commented on dz/7/MAKET_TABLE/index.html
> +                    Футбол (от англ. foot — ступня, ball — мяч) — командный вид спорта,
почему тире не через мнемоники?

2017-09-27 05:11 UTC, fd1-44-17 commented on dz/7/MAKET_DIV/index.html
> +                    Футбол (от англ. foot — ступня, ball — мяч) — командный вид спорта, в котором целью является забить мяч в ворота соперника ногами или другими частями тела (кроме рук) большее коли
тире должны быть с помощью html-сущностей (мнемоник)

2017-10-04 07:05 UTC, MorozovAl commented
please review

2017-10-05 11:59 UTC, fd1-44-17 approved these changes

2017-10-05 11:59 UTC, merged