2509 home
fd1-44-17-group/morozoval pull request #15
Opened 2017-09-26 21:04 UTC by MorozovAl

please review

2017-09-27 05:14 UTC, fd1-44-17 requested changes

2017-09-27 05:14 UTC, fd1-44-17 commented on dz/7/MAKET_DIV/assets/css/style.css
> +@media screen and (max-width: 800px) {
400px

2017-09-27 05:14 UTC, fd1-44-17 commented on dz/7/MAKET_DIV/index.html
> +                    Футбол (от англ. foot — ступня, ball — мяч) — командный вид спорта, в котором целью является забить мяч в ворота соперника ногами или другими частями тела (кроме рук) большее коли
тире - через мнемоники

2017-09-27 05:14 UTC, fd1-44-17 commented on dz/7/MAKET_TABLE/index.html
> +                    Футбол (от англ. foot — ступня, ball — мяч) — командный вид спорта, в котором целью является забить мяч в ворота соперника ногами или другими частями тела (кроме рук) большее коли
тире через мнемоники

2017-09-28 09:06 UTC, MorozovAl commented
please review

2017-10-05 11:59 UTC, fd1-44-17 approved these changes

2017-10-05 11:59 UTC, fd1-44-17 commented
please resolve conflicts

2017-10-05 22:12 UTC, MorozovAl commented
@fd1-44-17 
please review

2017-10-16 07:02 UTC, merged