2709
fd1-44-17-group/morozoval pull request #16
Opened 2017-09-28 08:42 UTC by MorozovAl

plese review

2017-09-29 04:56 UTC, fd1-44-17 requested changes
не правильно подключены шрифты.

2017-09-29 04:56 UTC, fd1-44-17 commented on work/2709/3/index.html
> +        <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
в IE работать не будет.  Что я говорил по поводу описания и подключения шрифтов?

2017-09-29 04:56 UTC, fd1-44-17 commented on work/2709/4/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Catamaran" rel="stylesheet">
где должны быть подключены описания шрифтов?

2017-09-29 04:56 UTC, fd1-44-17 commented on work/2709/5/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Saira" rel="stylesheet">
опять шрифты

2017-09-29 04:56 UTC, fd1-44-17 commented on work/2709/6/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Saira" rel="stylesheet">
шрифты

2017-09-29 06:11 UTC, MorozovAl commented
please review

2017-10-05 12:00 UTC, fd1-44-17 approved these changes

2017-10-05 12:00 UTC, merged