Cloud, numbers, button, smile.
fd1-44-17-group/morozoval pull request #17
Opened 2017-09-28 22:03 UTC by MorozovAl

please review

2017-09-29 05:03 UTC, fd1-44-17 requested changes
Вцелом неплохо, но ошибки нужно исправить.

2017-09-29 05:03 UTC, fd1-44-17 commented on dz/8/1/index.html
> +        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
не правильно подключены шрифты.

2017-09-29 05:03 UTC, fd1-44-17 commented on dz/8/3/index.html
> +            <span style="color:orange">Отправить</span>
почему inline-стили?

2017-09-29 06:00 UTC, MorozovAl commented on dz/8/3/index.html
> +            <span style="color:orange">Отправить</span>
Потому, что тестировал и забыл убрать :(

2017-09-29 06:05 UTC, MorozovAl commented
please review

2017-10-09 05:17 UTC, fd1-44-17 approved these changes

2017-10-09 05:17 UTC, merged