animal_language
fd1-44-17-group/morozoval pull request #2
Opened 2017-09-04 08:20 UTC by MorozovAl

@fd1-44-17 
check class work!

2017-09-04 13:58 UTC, fd1-44-17 requested changes
работаем над ошибками

2017-09-04 13:58 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +            <p>Язык животных</p>
для чего в h1 вставлять p?

2017-09-04 13:58 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +        <meta charset="utf-8">
где title?

2017-09-04 13:58 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +            язык поз и телодвижений;
это должно быть списком, а не в один абзац

2017-09-04 13:58 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +            Важную роль в обмене информацией играет язык поз и телодвижений, а в нём самом - хвост и уши. Их многочисленные положения говорят о более тонких оттенках настроений и намерений хозяина.
минусы заменить на тире (мнемноники)

2017-09-06 06:19 UTC, MorozovAl commented
@fd1-44-17 
please review

2017-09-07 07:50 UTC, fd1-44-17 approved these changes

2017-09-07 07:50 UTC, merged