0409 home
fd1-44-17-group/morozoval pull request #3
Opened 2017-09-04 17:21 UTC by MorozovAl

@fd1-44-17 
please review!

2017-09-05 12:59 UTC, fd1-44-17 requested changes

2017-09-05 12:59 UTC, fd1-44-17 commented on dz/2/2.html
> +        <meta charset="utf-8">
а где тег title?

2017-09-05 12:59 UTC, fd1-44-17 commented on dz/2/DIARY.html
> +    &copy бородатый <a href="http://www.primera-club.ru/attachments/87284d1449413938-anekdot-anekdot.png"
не правильно использована мнемоника

2017-09-05 12:59 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +        <meta charset="utf-8">
где title?

2017-09-05 12:59 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +            <p>Каналы связи</p>
зачем p вставлять в заголовок?

2017-09-05 12:59 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +            <p>Язык животных</p>
зачем p вставлять в заголовок

2017-09-06 06:18 UTC, MorozovAl commented
@fd1-44-17 
please review

2017-09-07 07:50 UTC, fd1-44-17 approved these changes

2017-09-07 07:51 UTC, merged