first commit chess-div
fd1-44-17-group/morozoval pull request #9
Opened 2017-09-14 13:51 UTC by MorozovAl

please review

2017-09-15 05:30 UTC, fd1-44-17 requested changes

2017-09-15 05:30 UTC, fd1-44-17 commented on dz/4/assets/css/style.css
> +}
Зачем для нескольких классов указывать  background-image и background-repeat ?
эти свойства общие для всех .cell

2017-09-15 05:54 UTC, MorozovAl commented
please review

2017-09-17 18:58 UTC, fd1-44-17 approved these changes

2017-09-17 18:58 UTC, merged